version: 2

sources:
  - name: raw
    database: ecommerce_db
    schema: raw
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items

models:
  - name: fact_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null