version: 2

sources:
  - name: raw
    database: ecommerce_db
    schema: raw
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items

models:
  - name: stg_products
    description: "Staged product data from raw source"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: category
      - name: price
        tests:
          - not_null
      - name: description
      - name: created_at
  - name: stg_customers
    description: "Staged customer data from raw source"
    columns:
      - name: customer_id
        tests: 
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: email
  - name: stg_order_items
    description: "staged order item data from raw source"
    columns:
      - name: order_item_id
        description: "The id of the item ordered"
        tests: 
        - not_null
      - name: order_id
        description: "The id of the order"
        tests: 
        - unique
        - not_null
      - name: product_id
        description: "The id of the product ordered"
        tests: 
        - not_null
      - name: quantity
        description: "The amount of item ordered"
        tests: 
        - not_null
      - name: price
        description: "The price of item ordered"
        tests: 
        - not_null
      - name: total
        description: "The total sale amoutn of the item ordered"
        tests: 
        - not_null
  - name: stg_orders
    description: "staged order data from the raw source"
    columns:
      - name: order_id
        description: "The id of the order"
        tests: 
        - not_null
        - unique
      - name: customer_id
        description: "The customer id of the order"
        tests: 
        - not_null
      - name: order_date
        description: "The date the order was submitted"
        tests: 
        - not_null
      - name: status
        description: "The status of the order"
        tests: 
        - not_null
      - name: total_amount
        description: "cost to the customer for this order"
        tests: 
        - not_null
  - name: int_customer_orders
    description: "Intermediate model combining customer data with their order history"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: total_orders
        description: "Total number of orders placed by the customer"
      - name: total_spent
        description: "Total amount spent by the customer"
  - name: int_product_sales_metrics
    description: "Aggregated sales metrics for each product"
    columns:
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the product"
      - name: category
        description: "Product category"
      - name: price
        description: "Current price of the product"
      - name: description
        description: "Product description"
      - name: created_at
        description: "Timestamp when the product was created"
      - name: total_orders
        description: "Total number of orders containing this product"
      - name: total_quantity_sold
        description: "Total quantity of this product sold"
      - name: total_revenue
        description: "Total revenue generated by this product"
  - name: customer_mart
    description: "Customer data mart with segmentation"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: total_spent
        description: "Total amount spent by the customer"
      - name: customer_segment
        description: "Customer segment based on total spend"
        tests:
          - accepted_values:
              values: ['High Value', 'Medium Value', 'Low Value']
  - name: product_mart
    description: "Product data mart with performance metrics"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: total_revenue
        description: "Total revenue generated by the product"
      - name: product_performance
        description: "Product performance category based on total revenue"
        tests:
          - accepted_values:
              values: ['High Performing', 'Medium Performing', 'Low Performing']
  - name: sales_mart
    description: "Consolidated sales data mart"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: customer_segment
      - name: order_date
      - name: total_amount
      - name: product_id
      - name: product_name
      - name: product_category
      - name: quantity
      - name: unit_price
      - name: item_total
  - name: dim_customers
    description: "Customer dimension table"
    columns:
      - name: customer_id
        description: "The unique identifier for the customer"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name"
      - name: last_name
        description: "Customer's last name"
      - name: email
        description: "Customer's email address"
        tests:
          - not_null
  - name: dim_products
    description: "Product dimension table"
    columns:
      - name: product_id
        description: "The unique identifier for the product"
        tests:
          - unique
          - not_null
      - name: name
        description: "Product name"
        tests:
          - not_null
      - name: category
        description: "Product category"
      - name: price
        description: "Current price of the product"
        tests:
          - not_null
      - name: description
        description: "Product description"
      - name: created_at
        description: "Timestamp when the product was created"

  - name: dim_dates
    description: "Date dimension table"
    columns:
      - name: date_id
        description: "Unique identifier for the date"
        tests:
          - unique
          - not_null
      - name: date
        description: "Calendar date"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year of the date"
      - name: month
        description: "Month of the date"
      - name: day
        description: "Day of the month"
      - name: day_of_week
        description: "Day of the week (1-7)"
      - name: quarter
        description: "Quarter of the year"

  - name: fact_orders
    description: "Fact table for orders"
    columns:
      - name: order_id
        description: "Unique identifier for the order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to dim_customers"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: date_id
        description: "Foreign key to dim_dates"
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_id
      - name: status
        description: "Current status of the order"
      - name: total_amount
        description: "Total amount of the order"
        tests:
          - not_null
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
  - name: fact_order_items
    description: "Fact table for order items"
    columns:
      - name: order_item_id
        description: "Unique identifier for the order item"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to fact_orders"
        tests:
          - not_null
          - relationships:
              to: ref('fact_orders')
              field: order_id
      - name: product_id
        description: "Foreign key to dim_products"
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: quantity
        description: "Quantity of the product ordered"
        tests:
          - not_null
      - name: price
        description: "Price of the product at the time of order"
        tests:
          - not_null
      - name: total
        description: "Total amount for this order item"
        tests:
          - not_null